# Generated by Django 4.1.6 on 2023-03-25 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product')),
                ('category', models.CharField(choices=[('Medicines', 'Medicines'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Other', 'Other')], default='Other', max_length=100, verbose_name='Product Category')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Review Text')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Product Raiting')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.product', verbose_name='Product')),
            ],
        ),
    ]
